### ISSUE TITLE
MOS scope (marksman kit) reticle is cluttered

### ISSUE THREAD

**Issue by fauxhawkfox** [Mjolnir64/FNF#18]
reported by FLying-FINN

the current marksman MOS scope is cluttered and sometimes difficult to use

suggested alternatives:
- optic_khs_blk
- optic_ams

**Comment by Mjolnir64** [comment]
Current MOS has a good level of zoom for FNF, don't want the marksman to be too powerful compared to the regular infantry. Personally, I've never had any issues using the MOS - don't think it's very cluttered, can still see round impacts fine. Can look at optics and see if there are others that look better and accomplish the same things. Low priority as of now.

**Comment by fauxhawkfox** [comment]
AMS is a vanilla scope w/ mildots and decent magnification
SU430 would fit more with the DMR weaponry at 4x mag
