### ISSUE TITLE
INDFOR guns and body armor underpowered as compared to OPFOR (AK74vsAK47)

### ISSUE THREAD

**Issue by fauxhawkfox** [Mjolnir64/FNF#19]
29ID Nelson: 09/25 EU Round 2

The AK74 vs AK47 matchup seemed unbalanced between INDFOR and OPFOR. INDFOR seemed to lose multiple 1 on 1 firefights despite their best efforts.

`FNF_Ark_2020_09_23_ADSector_EU.ruha`

**Comment by Mjolnir64** [comment]
Armor values are the same, will need good testing to see if there is actually a significant difference between the performance of RHS 7.62x39 and 5.45x39 that needs to be accounted for. Could always be that the OPFOR players outshot the INDFOR players. Need more data.
