### ISSUE TITLE
Please do not use vanilla vehicles vs RHS vehicles or MAT

### ISSUE THREAD

**Issue by fauxhawkfox** [Mjolnir64/FNF#20]
EU round 3

Vanilla vehicles vs RHS weaponry put RHS MAT at a big disadvantage, less effective against vanilla vehicle's armor

Suggest pairing vanilla MAT / statics against vanilla vehicle assets

`FNF_FLying-FINN_ViLaBaoPoLa_24_September_2020_Uplink_EU.vt7`

**Comment by Mjolnir64** [comment]
Mission reviewers will have to catch things like this. Have had many discussions in the past around this and decided to keep Vanilla separate from RHS. New mission makers will have to understand this.
