### ISSUE TITLE
Add the terrain names for Lythium and Al Rayak to the ACEX fortify color list

### ISSUE THREAD

**Issue by Mjolnir64** [Mjolnir64/FNF#33]
This system works by checking the name of the current terrain with https://community.bistudio.com/wiki/worldName and if it is equal to a desert terrain, the color of the player placeable fortifications is changed to tan - default is green. 

Pertinent line: https://github.com/Mjolnir64/FNF/blob/d038b10558c8bda3262f0882336029982e6911ea/FNF_MissionTemplate.VR/server/init/fn_fortifyServer.sqf#L7

**Comment by fauxhawkfox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add new terrains for GRAD Trenches](https://trello.com/c/LGikh7Rv/24-add-new-terrains-for-grad-trenches)

**Comment by Mjolnir64** [comment]
https://github.com/Mjolnir64/FNF/commit/8d87b00d5596809ce68a8fe6f1ea383351a4cbee
