### ISSUE TITLE
Automatic marking for custom buildings and bridges

### ISSUE THREAD

**Issue by fauxhawkfox** [Mjolnir64/FNF#38]
initServer functionality to automatically place markers representing custom buildings and bridges for consistency

**Comment by fauxhawkfox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Auto mark custom buildings script](https://trello.com/c/7TPfJCOC/8-auto-mark-custom-buildings-script)

**Comment by Mjolnir64** [comment]
Should be reviewing and commiting this tonight
