### ISSUE TITLE
Add more strict requirements to the player start boundary function

### ISSUE THREAD

**Issue by Mjolnir64** [Mjolnir64/FNF#41]
https://github.com/Mjolnir64/FNF/blob/b4210db5d91de3a79d1377f095369a4b15956a48/FNF_MissionTemplate.VR/client/restrictions/fn_startBoundary.sqf

**Comment by indig0fox** [comment]
more restrictive teleportation during last 10 seconds & warnings from staff have all but eliminated occurrences of people jumping the safe zone boundary.
