### ISSUE TITLE
Test mission time left accounting for admin changes in safe start time

### ISSUE THREAD

**Issue by Mjolnir64** [Mjolnir64/FNF#42]
**What needs to be tested:**

A variable was added a bit ago to track how long safe start lasted, and then adjust the mission timer based on that variable. Variable gets created on server and sent to other clients here: 

https://github.com/Mjolnir64/FNF/blob/b4210db5d91de3a79d1377f095369a4b15956a48/FNF_MissionTemplate.VR/server/init/fn_serverSafety.sqf#L26

Variable was added to the server's check of the time remaining here:
https://github.com/Mjolnir64/FNF/blob/b4210db5d91de3a79d1377f095369a4b15956a48/FNF_MissionTemplate.VR/server/end/fn_checkTime.sqf#L6

Variable was added to the client's check of the time remaining here:
https://github.com/Mjolnir64/FNF/blob/b4210db5d91de3a79d1377f095369a4b15956a48/FNF_MissionTemplate.VR/client/misc/fn_clientTime.sqf#L8

**Expected behavior of the test:**
The client mission time left display and the server mission timer should take into account the actual safe start time, rather than the safe start time set in the mission config.

**Comment by fauxhawkfox** [comment]
Looks good on dedicated.
Works as expected. Modifying the f_var_mission_timer variable during safe start to shorten it, waiting for safe start to finish, and evaluating the resulting `(phx_missionTimelimit * 60) + phx_safetyEndTime;` shows that the mission run time was correctly decreased below the standard 3900 seconds and, in this instance, is 3421 seconds instead.
