### ISSUE TITLE
Test CBA XEH, InitPost EH locality

### ISSUE THREAD

**Issue by Mjolnir64** [Mjolnir64/FNF#44]
**What needs to be tested:**
Most of the CBA InitPost XEH's we use were changed from a global 'init' to 'clientInit' or 'serverInit' so locality checks aren't needed within the init code.

Relevant lines:
https://github.com/Mjolnir64/FNF/blob/f5d894bd405dc3627b7bdf40bbae66933856d708/FNF_MissionTemplate.VR/description/cfgEventHandlers.hpp#L1-L26

**Expected behavior of the test:**
This system should work exactly the same as before, but with less overhead.

**Comment by fauxhawkfox** [comment]
I've used this exact setup for the assets mods thus far, and it appears to be set up correctly. Tested MH-6M (still allows NVS), Humvee w/ LRAS, M1117 (DTV only). The LRAS PIP is still thermal equipped, but using the optics only allows DTV viewing. Good to go.
