### ISSUE TITLE
Define admin IDs via addon with global variable to prevent adjustment in mission framework

### ISSUE THREAD

**Issue by indig0fox** [Mjolnir64/FNF#48]
SteamID64 values for staff members used in defineTyping, to be used in patch/marker help assignment. Stored in framework and not vetted means there's danger in that list being modified by mission maker. Could we sideload this value in so we only have to update it in one place and its secured serverside?

**Comment by Mjolnir64** [comment]
Either loading it via an addon or enabling file patching on the server and reading it from a file.

**Comment by indig0fox** [comment]
Methodology for reading dynamically via url_fetch extension, param query to serverside database

MySql instance with playerUID, name, and role in a table. index.php page that supports a playerUID query param. dynamically fetch the player info based on the results of the query.

i set up a url_fetch.sqf script for local testing wth the x64 url_fetch extension published by KillzoneKid, found here http://killzonekid.com/arma-extension-url_fetch-dll-v2-0/
i modified it to, upon successful result (return from DB), save key=uid value=_resultarray into a global variable "staffInfo", type hashmap
in this server init, it also creates an every 180 seconds (3 mins) per frame handler that will run the url_fetch script to poll (http://ops.fridaynightfight.org/9062staff/?playerUID=%1) with the playerUID of allPlayers.


initially, i had all of the staff data in a big array just hosted on a static page. but all the extensions i looked at for http requests truncated the array when returned, which broke parsing and left incomplete data. the two i could find that supported paged results to a result array froze or crashed my game. i needed a solution that limited how much data needed to be pulled per GET. a dynamic page using a param value is perfect for this scenario.
i also needed to make sure that if a staff member JIPs during safe start due to d/c or crash, that they are appropriately labeled within a reasonable period of time, hence the periodic poll against allPlayers.

```sqf
// serverInit
if (isServer) then {
    missionNamespace setVariable["staffInfo", createHashMap];

    pollStaffInfo = [{
        {
            _uid = getPlayerUID _x;
            [_uid, format["...?playerUID=%1", _uid]] execVM "url_fetch.sqf";
        } forEach allPlayers;

        publicVariable "staffInfo";
    }, 180] call CBA_fnc_addPerFrameHandler;
```

```sqf
// supporting script url_fetch.sqf
if (isServer) then {
    params ["_uid", "_url"];
    private "_result";
    waitUntil {
        if ("url_fetch" callExtension format [
            "%1",
            _url
        ] == "OK") exitWith {true};
        false
    };
    waitUntil {
        _result = "url_fetch" callExtension "OK";
        if (_result != "WAIT") exitWith {true};
        false
    };
    if (_result == "ERROR") exitWith {
        //deal with error here
        diag_log format [
            ">>> [url_fetch v2.0] >>> ERROR: %1; ARGUMENTS: %2",
            "url_fetch" callExtension "ERROR",
            _url
        ];
    };
    //deal with result here
    diag_log format [
        ">>> [url_fetch v2.0] >>> RESULT: %1",
        _result
    ];
	if (_result != "") then {(missionNamespace getVariable "staffInfo") set [_uid, _result]};
};
```

**Comment by indig0fox** [comment]
need to establish best methodology:

settings addon, which is serverside but machine specific, and pack/unpack adds a small level of familiarity requirement for changes
reading from a file, which is also machine specific and requires extension
reading from web, which can be run from any server but is a more complex implementation

**Comment by indig0fox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Technical Team 2021-06-xx](https://trello.com/c/OankOLxr/64-technical-team-2021-06-xx)

**Comment by Mjolnir64** [comment]
Addon created in https://github.com/Mjolnir64/FNF/commit/dcaa3d7272004bb9eee9195d2791e7c541270b63
Added 'fnf' variable tag to 'staffInfo' var and deleted phx_fnc_defineStaff
