### ISSUE TITLE
Add a Kill counter to the Spectator cam using the ACEX kill Counter

### ISSUE THREAD

**Issue by Mallen-git** [Mjolnir64/FNF#49]
Use the ACEX kill counter to track kills and display them on the screen when they are in dead and spectator to stop people asking in teamspeak afterwards

**Comment by fauxhawkfox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FNF Kill Tracker for spectator](https://trello.com/c/Jfdl1sju/8-fnf-kill-tracker-for-spectator)
