### ISSUE TITLE
Evaluate checks for sandbags only on building rooftops (above AGL)

### ISSUE THREAD

**Issue by indig0fox** [Mjolnir64/FNF#50]
Concerns over gameplay being affected by building bunkers, etc, on rooftops. Limit build capabilities when not within 2m of ground level?

**Comment by Mjolnir64** [comment]
I've restricted it before and found things to be more interesting when players could build higher up

**Comment by fauxhawkfox** [comment]
It's just to limit the larger emplacements from being placed, like a full-size bunker. Sandbags are fine, Hescos are maybe, two story camo bunker should be a no

**Comment by Mjolnir64** [comment]
Changed in commit https://github.com/Mjolnir64/FNF/commit/e0020892684317c4b9fcc765ebd73ec77d6f6956
Uses PositionATL, so the object has to be terrain level. You won't be able to build on rocks. If building on rocks is a wanted ability, then I can check if there is any object inheriting from 'Rocks_base_F' class directly underneath the fortification piece.
