### ISSUE TITLE
Enhanced Movement Rework not configured for WW2

### ISSUE THREAD

**Issue by lusod** [Mjolnir64/FNF#66]
**Problem Statement**
Enhanced Movement Reworks blacklist is not up to date for WW2. The default blacklist included in the mod only blacklists vanilla objects (i.e. barbed wire fence, razorwire). Meaning that maps using the WW2 barbwire lets the player just vault over the wire.

**To Reproduce**
1. Open up the WW2 template mission file
2. Place barbedwire from WW2 mods
3. Host local server and pick a slot
4. Walk to barbedwire and vault over it.

**Expected behavior**
Player is stopped from vaulting over, simply jumps in front of the wire/fence

**Additional context**
String of objects that should be blocked by EMR. Can be put into cba_settings.sqf and fixes issue.
```sqf
"Land_I44_Buildings_Barbedwire,Land_I44_Buildings_Barbedwire2,Land_WW2_Wire_Bruno,Land_WW2_Wire_2,WW2_BET_Bwire_2,WW2_BET_Bwire_3,WW2_BET_Bwire_4,Land_fow_Barbedwire,Land_I44_Buildings_Wirefence"
```

**Comment by Mjolnir64** [comment]
Thanks, will get that set.

**Comment by Mjolnir64** [comment]
https://github.com/Mjolnir64/FNF/commit/26bae233543701249e609da868d835cfc6e0eedb
