### ISSUE TITLE
Several issues with WEAPONS_SOVIET.sqf

### ISSUE THREAD

**Issue by lusod** [Mjolnir64/FNF#82]
**Main issue**
WEAPONS_SOVIET.sqf gives the riflemen AK-74Ns, however, it gives them 7.62x39mm ammo, which isn't compatible.

This is very easy to fix, just remove line 5 and 6 (see screenshot)
![image](https://user-images.githubusercontent.com/25372280/124963085-aca47880-e01f-11eb-9910-6f8f96c55f21.png)
This will make it use the 5.45 mags in the WEAPONS_RU.sqf, which should be compatible. 

**Historical inaccuracies**
The 5.45 mags are 7N10, and according to [RHS's wiki](http://www.rhsmods.org/w/firearmsammo), the 7N10 ammo started being used in 1992, which of course is after the Soviet Union.

As well, the PKP started being produced in 2001, so it doesn't make much sense that the MMG gunners get it.

Consider replacing the rifle ammo with 7N6 or 7N6M.
Consider replacing PKP with PKM.

**Additional context**
v2.3.0 beta 1

**Comment by Mjolnir64** [comment]
Fixed. Thanks for the report.
https://github.com/Mjolnir64/FNF/commit/6f17f8816f14d8dc9de6d666becb084fc770f04d
