### ISSUE TITLE
dropped flag maintains altitude, making inaccessible if not reachable

### ISSUE THREAD

**Issue by indig0fox** [Mjolnir64/FNF#84]
need handler to snap to surface periodically in case left at upper story of now-collapsed building, etc
must respect ASL (water level) to not go underwater, is already present, but should snap to surface at land

**Comment by Mjolnir64** [comment]
Forgot to post it here, accounted for in https://github.com/Mjolnir64/FNF/commit/c51cbae203b94e1d413a5109ad0cbfd0da6487d2

Checks every second if the flag is touching the ground, if not, finds an empty position near the x,y pos of the flag and moves the flag there
